apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
      app: blue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-deploy
  template:
    metadata:
      labels:
        app: blue-deploy
        color: blue
    spec:
      containers:
      - name: blue-deploy
        image: ambarbhore1234/rmm-agent:45
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
