apiVersion: v1
kind: Service
metadata:
  name: rmm-agent-jfrog-deploy
spec:
  type: NodePort
  selector:
    app: rmm-agent-jfrog-deploy
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010
