apiVersion: v1
kind: Service
metadata:
  name: rmm-agent-blue-deploy
spec:
  type: NodePort
  selector:
    app: blue-deploy
    color: blue
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010
